### ISSUE TITLE
完善机器人模型，提交给TC审核

### ISSUE THREAD

**Issue by TTimelord** [MosHumanoid/THMOS-Webots#5]
archive需要按照要求修改

**Comment by Zcyyy** [comment]
1.增加传感器Gyro。
2.如果可以的话可以加上脚底压力传感器。
3.初始姿态问题。

**Comment by WooQi57** [comment]
gyro和足底传感器已经加上了

**Comment by Zcyyy** [comment]
好的，模型没有大问题了，小问题直接提交commit，这个issue就关闭了。
